#!/bin/bash

# Function app and storage account names must be unique.
storageName=azimagepredstor
functionAppName=azImagePredictor
myResourceGroup=maddendeavor-us
region=eastus
pythonVersion=3.10

# Create a resource group.
az group create --name $myResourceGroup --location $region

# Create an Azure storage account in the resource group.
az storage account create \
  --name $storageName \
  --location $region \
  --resource-group $myResourceGroup \
  --sku Standard_LRS \
  --allow-blob-public-access false

# Create a serverless function app in the resource group.
az functionapp create \
  --name $functionAppName \
  --storage-account $storageName \
  --consumption-plan-location $region \
  --resource-group $myResourceGroup \
  --os-type Linux \
  --runtime python \
  --runtime-version $pythonVersion \
  --functions-version 4
